export const categoryConstants = {
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  SHOW_CATEGORY: 'SHOW_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  LIST_CATEGORY: 'LIST_CATEGORY',
};