export const postConstants = {
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAILED: 'CREATE_POST_FAILED',
  SHOW_POST: 'SHOW_POST',
  GET_POST: 'GET_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  LIST_POST: 'LIST_POST',
  LIST_POST_SUCCESS: 'LIST_POST_SUCCESS',
  LIST_POST_FAILED: 'LIST_POST_FAILED'
};