export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const SHOW_CATEGORY = 'SHOW_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ERROR = 'ERROR';