export const postConstants = {
  CREATE_POST_SUCCESS: 'CREATE_POST',
  SHOW_POST: 'SET_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  LIST_POST: 'LIST_POST',
  ERROR: 'ERROR',
};