export const postConstants = {
  POST_LIST: 'POST_LIST',
  PAGE_INFO: 'PAGE_INFO',
  ADD_POST: 'ADD_POST',
  GET_POST: 'GET_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  ERROR: 'ERROR',
};